.TH "Topology Objects" 3 "Thu Jan 17 2013" "Version 1.6.1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Topology Objects \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBhwloc_obj_memory_s\fP"
.br
.RI "\fIObject memory\&. \fP"
.ti -1c
.RI "struct \fBhwloc_obj_memory_s::hwloc_obj_memory_page_type_s\fP"
.br
.RI "\fIArray of local memory page types, \fCNULL\fP if no local memory and \fCpage_types\fP is 0\&. \fP"
.ti -1c
.RI "struct \fBhwloc_obj\fP"
.br
.RI "\fIStructure of a topology object\&. \fP"
.ti -1c
.RI "union \fBhwloc_obj_attr_u\fP"
.br
.RI "\fIObject type-specific Attributes\&. \fP"
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_bridge_attr_s\fP"
.br
.RI "\fIBridge specific Object Attribues\&. \fP"
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_cache_attr_s\fP"
.br
.RI "\fICache-specific Object Attributes\&. \fP"
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_group_attr_s\fP"
.br
.RI "\fIGroup-specific Object Attributes\&. \fP"
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_osdev_attr_s\fP"
.br
.RI "\fIOS Device specific Object Attributes\&. \fP"
.ti -1c
.RI "struct \fBhwloc_obj_attr_u::hwloc_pcidev_attr_s\fP"
.br
.RI "\fIPCI Device specific Object Attributes\&. \fP"
.ti -1c
.RI "struct \fBhwloc_distances_s\fP"
.br
.RI "\fIDistances between objects\&. \fP"
.ti -1c
.RI "struct \fBhwloc_obj_info_s\fP"
.br
.RI "\fIObject info\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBhwloc_obj\fP * \fBhwloc_obj_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBhwloc_obj\fP* \fBhwloc_obj_t\fP"

.PP
Convenience typedef; a pointer to a struct \fBhwloc_obj\fP\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code\&.
