.TH "OpenFabrics-Specific Functions" 3 "24 Nov 2009" "Version 0.9.3rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenFabrics-Specific Functions \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "static inline \fBhwloc_cpuset_t\fP \fBhwloc_ibv_get_device_cpuset\fP (struct ibv_device *ibdev)"
.br
.RI "\fIGet the CPU set of logical processors that are physically close to device \fCibdev\fP. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "static inline \fBhwloc_cpuset_t\fP hwloc_ibv_get_device_cpuset (struct ibv_device * ibdev)\fC [static]\fP"
.PP
Get the CPU set of logical processors that are physically close to device \fCibdev\fP. For the given OpenFabrics device \fCibdev\fP, read the corresponding kernel-provided cpumap file and return the corresponding CPU set. This function is currently only implemented in a meaningful way for Linux; other systems will simply get a full cpuset. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
