.TH "hwloc_obj_attr_u::hwloc_misc_attr_s" 3 "24 Nov 2009" "Version 0.9.3rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hwloc_obj_attr_u::hwloc_misc_attr_s \- 
.PP
Misc-specific Object Attributes.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <hwloc.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBdepth\fP"
.br
.RI "\fIDepth of misc object. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Misc-specific Object Attributes. 
.SH "Field Documentation"
.PP 
.SS "unsigned \fBhwloc_obj_attr_u::hwloc_misc_attr_s::depth\fP"
.PP
Depth of misc object. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
