.TH "Helpers for manipulating linux kernel cpumap files" 3 "24 Nov 2009" "Version 0.9.3rc1" "Hardware Locality (hwloc)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helpers for manipulating linux kernel cpumap files \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBhwloc_cpuset_t\fP \fBhwloc_linux_parse_cpumap_file\fP (FILE *file)"
.br
.RI "\fIConvert a linux kernel cpumap file \fCfile\fP into hwloc CPU set. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBhwloc_cpuset_t\fP hwloc_linux_parse_cpumap_file (FILE * file)"
.PP
Convert a linux kernel cpumap file \fCfile\fP into hwloc CPU set. Might be used when reading CPU set from sysfs attributes such as topology and caches for processors, or local_cpus for devices. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Hardware Locality (hwloc) from the source code.
